baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  slogan: "Super Fast!"


menu:
  main:
  - name: Home
    pageRef: /
    weight: 10